<?xml version="1.0" encoding="utf-8"?><Database Name="master" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-AIUPKU9;Initial Catalog=master;Integrated Security=True" SettingsObjectName="ProjetWPF.Properties.Settings" SettingsPropertyName="masterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.admin" Member="admin">
    <Type Name="admin">
      <Column Name="Id_admin" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mot_de_passe" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Filiere" Member="Filiere">
    <Type Name="Filiere">
      <Column Name="Id_filiere" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nom_filiere" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Filiere_etudiant" Member="etudiant" ThisKey="Id_filiere" OtherKey="id_fil" Type="etudiant" />
      <Association Name="Filiere_Responsable" Member="Responsable" ThisKey="Id_filiere" OtherKey="filière" Type="Responsable" />
    </Type>
  </Table>
  <Table Name="dbo.etudiant" Member="etudiant">
    <Type Name="etudiant">
      <Column Name="cne" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="prenom" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="sexe" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="date_naiss" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="id_fil" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="Filiere_etudiant" Member="Filiere" ThisKey="id_fil" OtherKey="Id_filiere" Type="Filiere" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Responsable" Member="Responsable">
    <Type Name="Responsable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prenom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="filière" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="photo" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="Filiere_Responsable" Member="Filiere" ThisKey="filière" OtherKey="Id_filiere" Type="Filiere" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>